"""
@Project ：fms_predict_sdk_v2
@File    ：statusCode.py
@IDE     ：PyCharm
@Author  ：Tristen
@Date    ：2023/05/05 19:20
@Des     ：状态码
"""

TEST_PREDICTION_CONNECT_IS_READY = 2000000
TEST_PREDICTION_CONNECT_IS_READY_MSG = "waiting"
TEST_PREDICTION_CONNECT_IS_STARTED = 2000001
TEST_PREDICTION_CONNECT_IS_STARTED_MSG = "started"
TEST_PREDICTION_CONNECT_MOVEMENT_SWITCHED = 2000002
TEST_PREDICTION_CONNECT_MOVEMENT_SWITCHED_MSG = "switched_movement"
TEST_PREDICTION_CONNECT_MOVEMENT_PREDICTION = 2000003
TEST_PREDICTION_CONNECT_MOVEMENT_PREDICTION_MSG = "success"
TEST_PREDICTION_CONNECT_MOVEMENT_PREDICTION_SCORE = 2000004
TEST_PREDICTION_CONNECT_MOVEMENT_PREDICTION_SCORE_MSG = "success"
TEST_PREDICTION_CONNECT_MOVEMENT_IS_NEXT_TIMES = 2000005
TEST_PREDICTION_CONNECT_MOVEMENT_IS_NEXT_TIMES_MSG = "success"
TEST_PREDICTION_CONNECT_IS_CLOSED = 23000001
TEST_PREDICTION_CONNECT_IS_CLOSED_MSG = "success"

# 测试输入的数据
TEST_PREDICTION_CONNECT_TO_START = 2100001
TEST_PREDICTION_CONNECT_START_PREDICTION = 2100002
TEST_PREDICTION_CONNECT_MOVEMENT_DEEP_SQUAT = 2100010
TEST_PREDICTION_CONNECT_MOVEMENT_HURDLE_STEP = 2100011
TEST_PREDICTION_CONNECT_MOVEMENT_HURDLE_STEP_LEFT = 21000111
TEST_PREDICTION_CONNECT_MOVEMENT_HURDLE_STEP_RIGHT = 21000112
TEST_PREDICTION_CONNECT_MOVEMENT_INLINE_LUNGE = 2100012
TEST_PREDICTION_CONNECT_MOVEMENT_INLINE_LUNGE_LEFT = 21000121
TEST_PREDICTION_CONNECT_MOVEMENT_INLINE_LUNGE_RIGHT = 21000121
TEST_PREDICTION_CONNECT_MOVEMENT_SHOULDER_MOBILITY = 2100013
TEST_PREDICTION_CONNECT_MOVEMENT_SHOULDER_MOBILITY_LEFT = 21000131
TEST_PREDICTION_CONNECT_MOVEMENT_SHOULDER_MOBILITY_RIGHT = 21000132
TEST_PREDICTION_CONNECT_MOVEMENT_ACTIVE_STRAIGHT_LEG_RAISE = 2100014
TEST_PREDICTION_CONNECT_MOVEMENT_ACTIVE_STRAIGHT_LEG_RAISE_LEFT = 21000141
TEST_PREDICTION_CONNECT_MOVEMENT_ACTIVE_STRAIGHT_LEG_RAISE_RIGHT = 21000142
TEST_PREDICTION_CONNECT_MOVEMENT_TRUNK_STABILITY_PUSH_UP = 2100015
TEST_PREDICTION_CONNECT_MOVEMENT_ROTARY_STABILITY_QUADRUPED = 2100016
TEST_PREDICTION_CONNECT_MOVEMENT_ROTARY_STABILITY_QUADRUPED_LEFT = 21000161
TEST_PREDICTION_CONNECT_MOVEMENT_ROTARY_STABILITY_QUADRUPED_RIGHT = 21000162
TEST_PREDICTION_CONNECT_MOVEMENT_NEXT_TIMES = 21000100
TEST_PREDICTION_CONNECT_MOVEMENT_INPUT_DATA = 22000000
TEST_PREDICTION_CONNECT_TO_CLOSE = 23000000


# Exception
PARAMETER_MISSING = 40000000
PARAMETER_MISSING_MSG = "参数缺失"  # 参数缺失

DATA_DECODE_ERROR = 40000001
DATA_DECODE_ERROR_MSG = "数据格式错误无法解析"

PREDICTION_MOVEMENT_MISSING_ERROR = 40000002
PREDICTION_MOVEMENT_MISSING_ERROR_MSG = "需要先传递当前预测的动作码"  # 参数缺失

PREDICTION_MOVEMENT_TIMES_OUT_ERROR = 40000003
PREDICTION_MOVEMENT_TIMES_OUT_ERROR_MSG = "预测次数超过限制"
